version: '3'

services:
  postgres:
    container_name: ict-2021-postgres
    image: library/postgres:9.5.14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "15432:5432"
volumes:
  postgres-data:
